"""Compare every run under an output directory in one table.

Scans output/*/ for config.json, train.csv and eval/*.json and prints one row
per run. Generated by scanning rather than appended to by each run, so it is
always consistent, can be regenerated at any time, and two concurrent jobs can
never interleave rows into a shared file.

Examples:
    .venv/bin/python tools/summarize_runs.py
    .venv/bin/python tools/summarize_runs.py --out output/runs.csv
    .venv/bin/python tools/summarize_runs.py --sort mpjpe
"""

import _init_paths  # noqa: F401
import argparse
import csv
import json
from pathlib import Path

from _init_paths import REPO_ROOT
from mvface.output_dir import OutputDir

COLUMNS = ["run", "started", "git", "epochs", "best_epoch", "best_mpjpe_mm",
           "p_mpjpe_mm", "hz", "n_train", "n_val", "data"]


def last_row(csv_path: Path) -> dict | None:
    if not csv_path.is_file():
        return None
    with open(csv_path, newline="") as f:
        rows = list(csv.DictReader(f))
    return rows[-1] if rows else None


def best_epoch(csv_path: Path) -> tuple[int | None, float | None]:
    """Lowest val_mpjpe in train.csv -> (epoch, value)."""
    if not csv_path.is_file():
        return None, None
    best = (None, None)
    with open(csv_path, newline="") as f:
        for r in csv.DictReader(f):
            try:
                v = float(r["val_mpjpe"])
            except (KeyError, ValueError):
                continue
            if best[1] is None or v < best[1]:
                best = (int(r["epoch"]), v)
    return best


def summarize(run: OutputDir) -> dict | None:
    cfg = run.read_config() or {}
    ep, mpjpe = best_epoch(run.train_csv)
    last = last_row(run.train_csv)

    # Prefer the eval report's numbers when one exists -- it is measured on the
    # frozen split by eval.py, whereas train.csv is the in-loop estimate.
    ev = {}
    for cand in ("best", "last"):
        p = run.eval_json(cand)
        if p.is_file():
            ev = json.loads(p.read_text())
            break

    if not cfg and ep is None and not ev:
        return None                       # not a run directory

    data = cfg.get("data_root") or run.data_root() or ""
    return {
        "run": run.root.name,
        "started": (cfg.get("started") or "")[:16],
        "git": (cfg.get("git_sha") or "") + ("*" if cfg.get("git_dirty") else ""),
        "epochs": last["epoch"] if last else "",
        "best_epoch": ep if ep is not None else "",
        "best_mpjpe_mm": f"{ev.get('mpjpe_mm', mpjpe):.3f}"
                         if (ev.get("mpjpe_mm") or mpjpe) is not None else "",
        "p_mpjpe_mm": f"{ev['p_mpjpe_mm']:.3f}" if "p_mpjpe_mm" in ev else "",
        "hz": f"{ev['hz']:.1f}" if "hz" in ev else "",
        "n_train": cfg.get("n_train", ""),
        "n_val": cfg.get("n_val", ""),
        "data": Path(data).name if data else "",
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO_ROOT / "output"),
                    help="directory holding run directories")
    ap.add_argument("--out", default=None, help="also write the table to this CSV")
    ap.add_argument("--sort", default="run",
                    choices=["run", "started", "mpjpe"], help="sort key")
    args = ap.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        raise SystemExit(f"no such directory: {root}")

    rows = [r for r in (summarize(OutputDir(d)) for d in sorted(root.iterdir())
                        if d.is_dir()) if r]
    if not rows:
        raise SystemExit(f"no runs found under {root}")

    if args.sort == "mpjpe":
        rows.sort(key=lambda r: float(r["best_mpjpe_mm"] or "inf"))
    elif args.sort == "started":
        rows.sort(key=lambda r: r["started"])

    widths = {c: max(len(c), *(len(str(r[c])) for r in rows)) for c in COLUMNS}
    print("  ".join(c.ljust(widths[c]) for c in COLUMNS))
    print("  ".join("-" * widths[c] for c in COLUMNS))
    for r in rows:
        print("  ".join(str(r[c]).ljust(widths[c]) for c in COLUMNS))

    if args.out:
        out = Path(args.out); out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            w.writeheader(); w.writerows(rows)
        print(f"\n-> {out}")


if __name__ == "__main__":
    main()
